In [1]:
import numpy as np

In [3]:
a = np.array([[1,2,3,4],[-1,-3,-4,2],[0,1,9,3]])
a

array([[ 1,  2,  3,  4],
       [-1, -3, -4,  2],
       [ 0,  1,  9,  3]])

In [4]:
b = np.array([[1,2,3]]).T
b

array([[1],
       [2],
       [3]])

In [5]:
a+b

array([[ 2,  3,  4,  5],
       [ 1, -1, -2,  4],
       [ 3,  4, 12,  6]])

In [8]:
def forward(Z):
        return np.exp(Z)/np.sum(np.exp(Z)) 

In [9]:
forward(np.array([[1],[2],[3],[4]]))

array([[0.0320586 ],
       [0.08714432],
       [0.23688282],
       [0.64391426]])

In [11]:
np.argmax(np.array([[1],[2],[3],[4]]))
np.log(np.array([[1],[2],[3],[4]]))

array([[0.        ],
       [0.69314718],
       [1.09861229],
       [1.38629436]])