In [3]:
import numpy as np

In [4]:
def lin_reg(x, th, th0):
    return (np.dot(th.T,x) + th0) #Outputs a row vector for entire data 

def square_loss(x, y, th, th0):
    return (y - lin_reg(x, th, th0))**2

def mean_square_loss(x, y, th, th0):
    return np.mean(square_loss(x, y, th, th0), axis=1, keepdims=True)

In [13]:
print(np.mean((np.array([[1,2,3],[4,5,6]])), axis = 0, keepdims=True))

[[2.5 3.5 4.5]]


In [22]:
def d_lin_reg_th(x, th, th0):
    return x

def d_square_loss_th(x, y, th, th0):
    return 2 * (lin_reg(x, th, th0) - y) * d_lin_reg_th(x, th, th0)

def d_mean_square_loss_th(x, y, th, th0):
    return np.mean(d_square_loss_th(x, y, th, th0), axis = 1, keepdims = True)


In [23]:
a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array([[0,1,3,4],[-1,-4,6,0]])
a,b,a*b

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 0,  1,  3,  4],
        [-1, -4,  6,  0]]),
 array([[  0,   2,   9,  16],
        [ -5, -24,  42,   0]]))

In [24]:
def d_lin_reg_th0(x, th, th0):
    return 1
    
# Write a function that returns the gradient of square_loss(x, y, th, th0) with
# respect to th0.  It should be a one-line expression that uses lin_reg and
# d_lin_reg_th0.
def d_square_loss_th0(x, y, th, th0):
    return 2*(lin_reg((x, th, th0) - y))

# Write a function that returns the gradient of mean_square_loss(x, y, th, th0) with
# respect to th0.  It should be a one-line expression that uses d_square_loss_th0.
def d_mean_square_loss_th0(x, y, th, th0):
    return np.mean(d_square_loss_th0(x, y, th, th0), axis = 1, keepdims = True)


In [27]:
def ridge_obj(x, y, th, th0, lam):
    return np.mean(square_loss(x, y, th, th0), axis = 1, keepdims = True) + lam*np.linalg.norm(theta)**2


In [28]:
def sgd(X, y, J, dJ, w0, step_size_fn, max_iter):
    fs = []
    gs = []
    fs.append(J(X, y, w0))
    gs.append(dJ(X, y, w0))
    w = w0.copy()
    np.random.seed(0)
    for i in range(max_iter-1):
        k = np.random.randint(X.shape[1])
        w = w - step_size_fn(i)*(dJ(X, y, w))
        
        fs.append(J(X, y, w))
        gs.append(dJ(X, y, w))
        
    return w,fs,gs
