In [40]:
import numpy as np

In [41]:
def hinge_grad(a,y):
    return np.where(np.dot(y,a)>1, 0, -y)

In [42]:
activation = np.array([[-3]])
label = np.array([[1]])
print(hinge_grad(activation, label))

[[-1]]


In [61]:
#Calculating the gradient matrix
W = np.array([[1, -1, -2], [-1, 2, 1]])
data = np.array([[1,1]]).T
target = np.array([[0, 1, 0]]).T

def feed_forward(x,W):
    z = np.dot(W.T,x)
    return np.exp(z)/np.sum(np.exp(z), axis=0)
    

def find_grad_matrix(x,y,a,W):
    m = W.shape[0]
    diff = (a - y).T
    W_grad = x[0,0]*(diff)
    for i in range(m-1):
        W_grad = np.append(W_grad, x[i+1,0]*(diff), axis=0)
     
    return W_grad
    
    

In [63]:
A = feed_forward(data,W)
print(A)
W_grad = find_grad_matrix(data,target,A,W)
W = W - 0.5*W_grad
print(W)

[[0.24472847]
 [0.66524096]
 [0.09003057]]
[[ 0.87763576 -0.83262048 -2.04501529]
 [-1.12236424  2.16737952  0.95498471]]


In [65]:
print(feed_forward(data,W))

[[0.15918761]
 [0.77245284]
 [0.06835955]]
